#ifndef KERNEL_ARCH_BIOS_H
#define KERNEL_ARCH_BIOS_H

#define BIOS_VRAM (0xB8000)

#define BIOS_DATA_START (0xE0000)
#define BIOS_DATA_END   (0xFFFFF + 1)
#define BIOS_DATA_PAGES (DIV_UP(BIOS_DATA_END - BIOS_DATA_START, PAGE_SIZE))

#endif
